"""Initial migration

Revision ID: c1539b3038b7
Revises: 
Create Date: 2025-12-08 18:52:05.855172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1539b3038b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blush',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('message_data', sa.Text(), nullable=False),
    sa.Column('theme_config', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blush')
    # ### end Alembic commands ###
